quarkus.container-image.builder=jib
quarkus.container-image.group=${SIGNOMIX_IMAGE_GROUP:${signomix.image.group.default}}
quarkus.container-image.name=${SIGNOMIX_IMAGE_NAME:signomix-scheduler}
quarkus.container-image.tag=${SIGNOMIX_IMAGE_TAG:%release%}

quarkus.scheduler.start-mode=forced