quarkus.container-image.builder=jib
quarkus.container-image.group=${SIGNOMIX_IMAGE_GROUP:${signomix.image.group.default}}
quarkus.container-image.name=${SIGNOMIX_IMAGE_NAME:signomix-scheduler}
quarkus.container-image.tag=${SIGNOMIX_IMAGE_TAG:%release%}

quarkus.scheduler.start-mode=forced


## REST Clients
com.signomix.scheduler.adapters.driven.ReportClient/mp-rest/url=http://signomix-report:8080

## MQTT
#
mp.messaging.outgoing.commands.connector=smallrye-mqtt
mp.messaging.outgoing.commands.host=signomix-broker
mp.messaging.outgoing.commands.port=1883
mp.messaging.outgoing.commands.topic=signomix/events/commands
mp.messaging.outgoing.commands.server-name=signomix-broker
mp.messaging.outgoing.commands.merge=true

mp.messaging.outgoing.events.connector=smallrye-mqtt
mp.messaging.outgoing.events.host=signomix-broker
mp.messaging.outgoing.events.port=1883
mp.messaging.outgoing.events.topic=signomix/events/commands
mp.messaging.outgoing.events.server-name=signomix-broker
mp.messaging.outgoing.events.merge=true

mp.messaging.outgoing.devicecommands.connector=smallrye-mqtt
mp.messaging.outgoing.devicecommands.host=signomix-broker
mp.messaging.outgoing.devicecommands.port=1883
mp.messaging.outgoing.devicecommands.topic=signomix/events/device-commands
mp.messaging.outgoing.devicecommands.server-name=signomix-broker

mp.messaging.outgoing.adminemail.connector=smallrye-mqtt
mp.messaging.outgoing.adminemail.host=signomix-broker
mp.messaging.outgoing.adminemail.port=1883
mp.messaging.outgoing.adminemail.topic=signomix/mailing/admin-email
mp.messaging.outgoing.adminemail.server-name=signomix-broker

## MONITORING
signomix.monitoring.disk.free=${SIGNOMIX_DISK_FREE_MB:1000}

## LOGGING
quarkus.log.level=${SIGNOMIX_LOG_LEVEL:INFO}

## HTTP
quarkus.http.port=${PORT:8080}
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.access-control-allow-credentials=true
quarkus.http.access-log.enabled=true

